-- http://pokemondb.net/pokedex/
PokeBase = {
	{
		name 	= "Bulbasaur", 
		desc 	= "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 45,
		atk			= 49,
		def 		= 49,
		special		= 65,
		speed 		= 45,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 	= "Ivysaur",
		desc 	= "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 60,
		atk 		= 62,
		def 		= 63,
		special		= 80,
		speed 		= 60,
		evolvelvl	= 32,
		moveset 	= {
					  },
	},
	{
		name 		= "Venusaur",
		desc	 	= "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 80,
		atk 		= 82,
		def 		= 83,
		special		= 100,
		speed 		= 80,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Charmander",
		desc 		= "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
		type1	 	= 8,
		type2 		= 0,
		hp 			= 39,
		atk 		= 52,
		def 		= 43,
		special		= 50,
		speed 		= 65,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 		= "Charmeleon",
		desc 		= "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 58,
		atk 		= 64,
		def 		= 58,
		special		= 65,
		speed 		= 80,
		evolvelvl	= 36,
		moveset 	= {
					  },
	},
	{
		name 		= "Charizard",
		desc 		= "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
		type1 		= 8,
		type2 		= 12,
		hp 			= 78,
		atk 		= 84,
		def 		= 78,
		special		= 85,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Squirtle",
		desc 		= "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 44,
		atk 		= 48,
		def 		= 65,
		special		= 50,
		speed 		= 43,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 		= "Wartortle",
		desc 		= "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 59,
		atk 		= 63,
		def 		= 80,
		special		= 65,
		speed 		= 58,
		evolvelvl	= 36,
		moveset 	= {
					  },
	},
	{
		name 		= "Blastoise",
		desc 		= "A brutal Pokemon with pressurized water jets on its shell. They are used for high speed tackles.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 79,
		atk 		= 83,
		def 		= 100,
		special		= 85,
		speed 		= 78,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Caterpie",
		desc 		= "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
		type1 		= 13,
		type2 		= 0,
		hp 			= 45,
		atk 		= 30,
		def 		= 35,
		special		= 20,
		speed 		= 45,
		evolvelvl	= 7,
		moveset 	= {
					  },
	},
	{
		name 		= "Metapod",
		desc 		= "This Pokemon is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
		type1 		= 13,
		type2 		= 0,
		hp 			= 50,
		atk 		= 20,
		def 		= 55,
		special		= 25,
		speed 		= 30,
		evolvelvl	= 10,
		moveset 	= {
					  },
	},
	{
		name 		= "Butterfree",
		desc 		= "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
		type1 		= 13,
		type2 		= 12,
		hp 			= 60,
		atk 		= 45,
		def 		= 50,
		special		= 80,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Weedle",
		desc 		= "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
		type1 		= 13,
		type2 		= 11,
		hp 			= 40,
		atk 		= 35,
		def 		= 30,
		special		= 20,
		speed 		= 50,
		evolvelvl	= 7,
		moveset 	= {
					  },
	},
	{
		name 		= "Kakuna",
		desc 		= "Almost incapable of moving, this Pokemon can only harden its shell to protect itself from predators.",
		type1 		= 13,
		type2 		= 11,
		hp 			= 45,
		atk 		= 25,
		def 		= 50,
		special		= 25,
		speed 		= 35,
		evolvelvl	= 10,
		moveset 	= {
					  },
	},
	{
		name 		= "Beedrill",
		desc 		= "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
		type1 		= 13,
		type2 		= 11,
		hp 			= 65,
		atk 		= 90,
		def 		= 40,
		special		= 45,
		speed 		= 75,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Pidgey",
		desc 		= "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 40,
		atk 		= 45,
		def 		= 40,
		special		= 35,
		speed 		= 56,
		evolvelvl	= 18,
		moveset 	= {
					  },
	},
	{
		name 		= "Pidgeotto",
		desc 		= "Very protective of its sprawling territorial area, this Pokemon will fiercely peck at any intruder.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 63,
		atk 		= 60,
		def 		= 55,
		special		= 50,
		speed 		= 71,
		evolvelvl	= 36,
		moveset 	= {
					  },
	},
	{
		name 		= "Pidgeot",
		desc 		= "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 83,
		atk 		= 80,
		def 		= 75,
		special		= 70,
		speed 		= 101,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Rattata",
		desc 		= "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 30,
		atk 		= 56,
		def 		= 35,
		special		= 25,
		speed 		= 72,
		evolvelvl	= 20,
		moveset 	= {
					  },
	},
	{
		name 		= "Raticate",
		desc 		= "	It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 55,
		atk 		= 81,
		def 		= 60,
		special		= 50,
		speed 		= 97,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Spearow",
		desc 		= "	Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 40,
		atk 		= 60,
		def 		= 30,
		special		= 31,
		speed 		= 70,
		evolvelvl	= 20,
		moveset 	= {
					  },
	},
	{
		name 		= "Fearow",
		desc 		= "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 65,
		atk 		= 90,
		def 		= 65,
		special		= 61,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Ekans",
		desc 		= "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 35,
		atk 		= 60,
		def 		= 44,
		special		= 40,
		speed 		= 55,
		evolvelvl	= 22,
		moveset 	= {
					  },
	},
	{
		name 		= "Arbok",
		desc 		= "It is rumored that the ferocious warning markings on its belly differ from area to area.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 60,
		atk 		= 85,
		def 		= 69,
		special		= 65,
		speed 		= 80,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Pikachu",
		desc 		= "When several of these Pokemon gather, their electricity could build and cause lightning storms.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 35,
		atk 		= 55,
		def 		= 40,
		special		= 50,
		speed 		= 90,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Raichu",
		desc 		= "Its long tail serves as a ground to protect itself from its own high voltage power.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 60,
		atk 		= 90,
		def 		= 55,
		special		= 80,
		speed 		= 110,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Sandshrew",
		desc 		= "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 50,
		atk 		= 75,
		def 		= 85,
		special		= 20,
		speed 		= 40,
		evolvelvl	= 22,
		moveset 	= {
					  },
	},
	{
		name 		= "Sandslash",
		desc 		= "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 75,
		atk 		= 100,
		def 		= 110,
		special		= 45,
		speed 		= 65,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidoran F",
		desc 		= "Although small, its venomous barbs render this Pokemon dangerous. The female has smaller horns.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 55,
		atk 		= 47,
		def 		= 52,
		special		= 40,
		speed 		= 41,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidorina",
		desc 		= "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 70,
		atk 		= 62,
		def 		= 67,
		special		= 55,
		speed 		= 56,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidoqueen",
		desc 		= "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.",
		type1 		= 11,
		type2 		= 5,
		hp 			= 90,
		atk 		= 92,
		def 		= 87,
		special		= 75,
		speed 		= 76,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidoran M",
		desc 		= "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 46,
		atk 		= 57,
		def 		= 40,
		special		= 40,
		speed 		= 50,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidorino",
		desc 		= "An aggressive POKÈMON that is quick to attack. The horn on its head secretes a powerful venom.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 61,
		atk 		= 72,
		def 		= 57,
		special		= 55,
		speed 		= 65,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Nidoking",
		desc 		= "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.",
		type1 		= 11,
		type2 		= 5,
		hp 			= 81,
		atk 		= 102,
		def 		= 77,
		special		= 65,
		speed 		= 85,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Clefairy",
		desc 		= "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 70,
		atk 		= 45,
		def 		= 48,
		special		= 60,
		speed 		= 35,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Clefable",
		desc 		= "	A timid fairy Pokemon that is rarely seen. It will run and hide the moment it senses people.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 95,
		atk 		= 70,
		def 		= 73,
		special		= 90,
		speed 		= 60,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Vulpix",
		desc 		= "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 38,
		atk 		= 41,
		def 		= 40,
		special		= 50,
		speed 		= 65,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Ninetales",
		desc 		= "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 73,
		atk 		= 76,
		def 		= 75,
		special		= 81,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Jigglypuff",
		desc 		= "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 115,
		atk 		= 45,
		def 		= 20,
		special		= 25,
		speed 		= 20,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Wigglytuff",
		desc 		= "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 140,
		atk 		= 70,
		def 		= 45,
		special		= 50,
		speed 		= 45,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Zubat",
		desc 		= "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
		type1 		= 11,
		type2 		= 12,
		hp 			= 40,
		atk 		= 45,
		def 		= 35,
		special		= 30,
		speed 		= 55,
		evolvelvl	= 22,
		moveset 	= {
					  },
	},
	{
		name 		= "Golbat",
		desc 		= "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
		type1 		= 11,
		type2 		= 12,
		hp 			= 75,
		atk 		= 80,
		def 		= 70,
		special		= 65,
		speed 		= 90,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Oddish",
		desc 		= "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 45,
		atk 		= 50,
		def 		= 55,
		special		= 65,
		speed 		= 30,
		evolvelvl	= 21,
		moveset 	= {
					  },
	},
	{
		name 		= "Gloom",
		desc 		= "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 60,
		atk 		= 65,
		def 		= 70,
		special		= 75,
		speed 		= 40,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Vileplume",
		desc 		= "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 75,
		atk 		= 80,
		def 		= 85,
		special		= 90,
		speed 		= 50,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Paras",
		desc 		= "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.",
		type1 		= 13,
		type2 		= 9,
		hp 			= 35,
		atk 		= 70,
		def 		= 55,
		special		= 45,
		speed 		= 25,
		evolvelvl	= 24,
		moveset 	= {
					  },
	},
	{
		name 		= "Parasect",
		desc 		= "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.",
		type1 		= 13,
		type2 		= 9,
		hp 			= 60,
		atk 		= 95,
		def 		= 80,
		special		= 60,
		speed 		= 30,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Venonat",
		desc 		= "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.",
		type1 		= 13,
		type2 		= 11,
		hp 			= 60,
		atk 		= 55,
		def 		= 50,
		special		= 40,
		speed 		= 45,
		evolvelvl	= 31,
		moveset 	= {
					  },
	},
	{
		name 		= "Venomoth",
		desc 		= "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.",
		type1 		= 13,
		type2 		= 11,
		hp 			= 70,
		atk 		= 65,
		def 		= 60,
		special		= 75,
		speed 		= 90,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Diglett",
		desc 		= "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 10,
		atk 		= 55,
		def 		= 25,
		special		= 35,
		speed 		= 95,
		evolvelvl	= 26,
		moveset 	= {
					  },
	},
	{
		name 		= "Dugtrio",
		desc 		= "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 35,
		atk 		= 80,
		def 		= 50,
		special		= 50,
		speed 		= 120,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Meowth",
		desc 		= "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 40,
		atk 		= 45,
		def 		= 35,
		special		= 40,
		speed 		= 90,
		evolvelvl	= 28,
		moveset 	= {
					  },
	},
	{
		name 		= "Persian",
		desc 		= "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 65,
		atk 		= 70,
		def 		= 60,
		special		= 65,
		speed 		= 115,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Psyduck",
		desc 		= "While lulling its enemies with its vacant look, this wily POKÈMON will use psychokinetic powers.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 50,
		atk 		= 52,
		def 		= 48,
		special		= 50,
		speed 		= 55,
		evolvelvl	= 33,
		moveset 	= {
					  },
	},
	{
		name 		= "Golduck",
		desc 		= "Its slim and long limbs end in broad flippers. They are used for swimming gracefully in lakes.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 80,
		atk 		= 82,
		def 		= 78,
		special		= 80,
		speed 		= 85,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Mankey",
		desc 		= "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 40,
		atk 		= 80,
		def 		= 35,
		special		= 35,
		speed 		= 70,
		evolvelvl	= 28,
		moveset 	= {
					  },
	},
	{
		name 		= "Primeape",
		desc 		= "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 65,
		atk 		= 105,
		def 		= 60,
		special		= 60,
		speed 		= 95,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Growlithe",
		desc 		= "Very protective of its territory. It will bark and bite to repel intruders from its space.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 55,
		atk 		= 70,
		def 		= 45,
		special		= 50,
		speed 		= 60,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Arcanine",
		desc 		= "	A Pokemon that has been admired since the past for its beauty. It runs agilely as if on wings.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 90,
		atk 		= 110,
		def 		= 80,
		special		= 80,
		speed 		= 95,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Poliwag",
		desc 		= "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 40,
		atk 		= 50,
		def 		= 40,
		special		= 40,
		speed 		= 90,
		evolvelvl	= 25,
		moveset 	= {
					  },
	},
	{
		name 		= "Poliwhirl",
		desc 		= "	Capable of living in or out of water. When out of water, it sweats to keep its body slimy.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 65,
		atk 		= 65,
		def 		= 65,
		special		= 50,
		speed 		= 90,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Poliwrath",
		desc 		= "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.",
		type1 		= 2,
		type2 		= 4,
		hp 			= 90,
		atk 		= 95,
		def 		= 95,
		special		= 70,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Abra",
		desc 		= "Using its ability to read minds, it will identify impending danger and teleport to safety.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 25,
		atk 		= 20,
		def 		= 15,
		special		= 55,
		speed 		= 90,
		evolvelvl	= 16,
		moveset 	= {
					  },
	},
	{
		name 		= "Kadabra",
		desc 		= "	It emits special alpha waves from its body that induce headaches just by being close by.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 40,
		atk 		= 35,
		def 		= 30,
		special		= 70,
		speed 		= 105,
		evolvelvl	= 36,
		moveset 	= {
					  },
	},
	{
		name 		= "Alakazam",
		desc 		= "	Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 55,
		atk 		= 50,
		def 		= 45,
		special		= 95,
		speed 		= 120,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Machop",
		desc 		= "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 70,
		atk 		= 80,
		def 		= 50,
		special		= 35,
		speed 		= 35,
		evolvelvl	= 28,
		moveset 	= {
					  },
	},
	{
		name 		= "Machoke",
		desc 		= "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 80,
		atk 		= 100,
		def 		= 70,
		special		= 50,
		speed 		= 45,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Machamp",
		desc 		= "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 90,
		atk 		= 130,
		def 		= 80,
		special		= 65,
		speed 		= 55,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Bellsprout",
		desc 		= "A carnivorous Pokemon that traps and eats bugs. It uses its root feet to soak up needed moisture.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 50,
		atk 		= 75,
		def 		= 35,
		special		= 30,
		speed 		= 40,
		evolvelvl	= 21,
		moveset 	= {
					  },
	},
	{
		name 		= "Weepinbell",
		desc 		= "It spits out poison powder to immobilize the enemy and then finishes it with a spray of acid.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 65,
		atk 		= 90,
		def 		= 50,
		special		= 45,
		speed 		= 55,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Victreebel",
		desc 		= "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
		type1 		= 9,
		type2 		= 11,
		hp 			= 80,
		atk 		= 105,
		def 		= 65,
		special		= 70,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Tentacool",
		desc 		= "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.",
		type1 		= 2,
		type2 		= 11,
		hp 			= 40,
		atk 		= 40,
		def 		= 35,
		special		= 50,
		speed 		= 70,
		evolvelvl	= 30,
		moveset 	= {
					  },
	},
	{
		name 		= "Tentacruel",
		desc 		= "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
		type1 		= 2,
		type2 		= 11,
		hp 			= 80,
		atk 		= 70,
		def 		= 65,
		special		= 80,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Geodude",
		desc 		= "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
		type1 		= 7,
		type2 		= 5,
		hp 			= 40,
		atk 		= 80,
		def 		= 100,
		special		= 30,
		speed 		= 20,
		evolvelvl	= 25,
		moveset 	= {
					  },
	},
	{
		name 		= "Graveler",
		desc 		= "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
		type1 		= 7,
		type2 		= 5,
		hp 			= 55,
		atk 		= 95,
		def 		= 115,
		special		= 45,
		speed 		= 35,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Golem",
		desc 		= "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.",
		type1 		= 7,
		type2 		= 5,
		hp 			= 80,
		atk 		= 120,
		def 		= 130,
		special		= 55,
		speed 		= 45,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Ponyta",
		desc 		= "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 50,
		atk 		= 85,
		def 		= 55,
		special		= 65,
		speed 		= 90,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Rapidash",
		desc 		= "Very competitive, this POKÈMON will chase anything that moves fast in the hopes of racing it.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 65,
		atk 		= 100,
		def 		= 70,
		special		= 80,
		speed 		= 105,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Slowpoke",
		desc 		= "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.",
		type1 		= 2,
		type2 		= 6,
		hp 			= 90,
		atk 		= 65,
		def 		= 65,
		special		= 40,
		speed 		= 15,
		evolvelvl	= 37,
		moveset 	= {
					  },
	},
	{
		name 		= "Slowbro",
		desc 		= "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps.",
		type1 		= 2,
		type2 		= 6,
		hp 			= 95,
		atk 		= 75,
		def 		= 110,
		special		= 80,
		speed 		= 30,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Magnemite",
		desc 		= "Uses anti-gravity to stay suspended. Appears without warning and uses thunder wave and similar moves.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 25,
		atk 		= 35,
		def 		= 70,
		special		= 55,
		speed 		= 45,
		evolvelvl	= 30,
		moveset 	= {
					  },
	},
	{
		name 		= "Magneton",
		desc 		= "	Formed by several Magnemites linked together. They frequently appear when sunspots flare up.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 50,
		atk 		= 60,
		def 		= 95,
		special		= 70,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Farfetch'd",
		desc 		= "The sprig of green onions it holds is its weapon. It is used much like a metal sword.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 52,
		atk 		= 65,
		def 		= 55,
		special		= 58,
		speed 		= 60,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Doduo",
		desc 		= "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 35,
		atk 		= 85,
		def 		= 45,
		special		= 35,
		speed 		= 75,
		evolvelvl	= 31,
		moveset 	= {
					  },
	},
	{
		name 		= "Dodrio",
		desc 		= "	Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.",
		type1 		= 1,
		type2 		= 12,
		hp 			= 60,
		atk 		= 110,
		def 		= 70,
		special		= 60,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Seel",
		desc 		= "The protruding horn on its head is very hard. It is used for bashing through thick ice.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 65,
		atk 		= 45,
		def 		= 55,
		special		= 45,
		speed 		= 45,
		evolvelvl	= 34,
		moveset 	= {
					  },
	},
	{
		name 		= "Dewgong",
		desc 		= "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.",
		type1 		= 2,
		type2 		= 10,
		hp 			= 90,
		atk 		= 70,
		def 		= 80,
		special		= 70,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Grimer",
		desc 		= "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 80,
		atk 		= 80,
		def 		= 50,
		special		= 40,
		speed 		= 25,
		evolvelvl	= 38,
		moveset 	= {
					  },
	},
	{
		name 		= "Muk",
		desc 		= "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 105,
		atk 		= 105,
		def 		= 75,
		special		= 65,
		speed 		= 50,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Shellder",
		desc 		= "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 30,
		atk 		= 65,
		def 		= 100,
		special		= 25,
		speed 		= 40,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Cloyster",
		desc 		= "When attacked, it launches its horns in quick volleys. Its innards have never been seen.",
		type1 		= 2,
		type2 		= 10,
		hp 			= 50,
		atk 		= 95,
		def 		= 180,
		special		= 45,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Gastly",
		desc 		= "Almost invisible, this gaseous Pokemon cloaks the target and puts it to sleep without notice.",
		type1 		= 14,
		type2 		= 11,
		hp 			= 30,
		atk 		= 35,
		def 		= 30,
		special		= 100,
		speed 		= 80,
		evolvelvl	= 25,
		moveset 	= {
					  },
	},
	{
		name 		= "Haunter",
		desc 		= "Because of its ability to slip through block walls, it is said to be from another dimension.",
		type1 		= 14,
		type2 		= 11,
		hp 			= 45,
		atk 		= 50,
		def 		= 45,
		special		= 115,
		speed 		= 95,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Gengar",
		desc 		= "Under a full moon, this Pokemon likes to mimic the shadows of people and laugh at their fright.",
		type1 		= 14,
		type2 		= 11,
		hp 			= 65,
		atk 		= 60,
		def 		= 60,
		special		= 130,
		speed 		= 110,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Onix",
		desc 		= "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.",
		type1 		= 7,
		type2 		= 5,
		hp 			= 35,
		atk 		= 45,
		def 		= 160,
		special		= 30,
		speed 		= 70,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Drowzee",
		desc 		= "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 60,
		atk 		= 48,
		def 		= 45,
		special		= 90,
		speed 		= 42,
		evolvelvl	= 26,
		moveset 	= {
					  },
	},
	{
		name 		= "Hypno",
		desc 		= "When it locks eyes with an enemy, it will use a mix of psi moves such as hypnosis and confusion.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 85,
		atk 		= 73,
		def 		= 70,
		special		= 115,
		speed 		= 67,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Krabby",
		desc 		= "Its pincers are not only powerful weapons, they are used for balance when walking sideways.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 30,
		atk 		= 105,
		def 		= 90,
		special		= 25,
		speed 		= 50,
		evolvelvl	= 28,
		moveset 	= {
					  },
	},
	{
		name 		= "Kingler",
		desc 		= "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 55,
		atk 		= 130,
		def 		= 115,
		special		= 50,
		speed 		= 75,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Voltorb",
		desc 		= "Usually found in power plants. Easily mistaken for a okÈ ball, they have zapped many people.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 40,
		atk 		= 30,
		def 		= 50,
		special		= 55,
		speed 		= 100,
		evolvelvl	= 30,
		moveset 	= {
					  },
	},
	{
		name 		= "Electrode",
		desc 		= "It stores electric energy under very high pressure. It often explodes with little or no provocation.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 60,
		atk 		= 50,
		def 		= 70,
		special		= 80,
		speed 		= 140,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Exeggcute",
		desc 		= "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.",
		type1 		= 9,
		type2 		= 6,
		hp 			= 60,
		atk 		= 40,
		def 		= 80,
		special		= 60,
		speed 		= 40,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Exeggutor",
		desc 		= "Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.",
		type1 		= 9,
		type2 		= 6,
		hp 			= 95,
		atk 		= 95,
		def 		= 85,
		special		= 125,
		speed 		= 55,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Cubone",
		desc 		= "Because it never removes its skull helmet, no one has ever seen this Pokemon's real face.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 50,
		atk 		= 50,
		def 		= 95,
		special		= 40,
		speed 		= 35,
		evolvelvl	= 28,
		moveset 	= {
					  },
	},
	{
		name 		= "Marowak",
		desc 		= "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.",
		type1 		= 5,
		type2 		= 0,
		hp 			= 60,
		atk 		= 80,
		def 		= 110,
		special		= 50,
		speed 		= 45,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Hitmonlee",
		desc 		= "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 50,
		atk 		= 120,
		def 		= 53,
		special		= 35,
		speed 		= 87,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Hitmonchan",
		desc 		= "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.",
		type1 		= 4,
		type2 		= 0,
		hp 			= 50,
		atk 		= 105,
		def 		= 79,
		special		= 35,
		speed 		= 76,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Lickitung",
		desc 		= "	Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 90,
		atk 		= 55,
		def 		= 75,
		special		= 60,
		speed 		= 30,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Koffing",
		desc 		= "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 40,
		atk 		= 65,
		def 		= 95,
		special		= 60,
		speed 		= 35,
		evolvelvl	= 35,
		moveset 	= {
					  },
	},
	{
		name 		= "Weezing",
		desc 		= "	Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years.",
		type1 		= 11,
		type2 		= 0,
		hp 			= 65,
		atk 		= 90,
		def 		= 120,
		special		= 85,
		speed 		= 60,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Rhyhorn",
		desc 		= "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.",
		type1 		= 5,
		type2 		= 7,
		hp 			= 80,
		atk 		= 85,
		def 		= 95,
		special		= 30,
		speed 		= 25,
		evolvelvl	= 42,
		moveset 	= {
					  },
	},
	{
		name 		= "Rhydon",
		desc 		= "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.",
		type1 		= 5,
		type2 		= 7,
		hp 			= 105,
		atk 		= 130,
		def 		= 120,
		special		= 45,
		speed 		= 40,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Chansey",
		desc 		= "A rare and elusive POKÈMON that is said to bring happiness to those who manage to get it.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 250,
		atk 		= 5,
		def 		= 5,
		special		= 35,
		speed 		= 50,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Tangela",
		desc 		= "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.",
		type1 		= 9,
		type2 		= 0,
		hp 			= 65,
		atk 		= 55,
		def 		= 115,
		special		= 100,
		speed 		= 60,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Kangaskhan",
		desc 		= "The infant rarely ventures out of its mother's protective pouch until it is 3 years old.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 105,
		atk 		= 95,
		def 		= 80,
		special		= 40,
		speed 		= 90,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Horsea",
		desc 		= "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 30,
		atk 		= 40,
		def 		= 70,
		special		= 70,
		speed 		= 60,
		evolvelvl	= 32,
		moveset 	= {
					  },
	},
	{
		name 		= "Seadra",
		desc 		= "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 55,
		atk 		= 65,
		def 		= 95,
		special		= 95,
		speed 		= 85,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Goldeen",
		desc 		= "	Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 45,
		atk 		= 67,
		def 		= 60,
		special		= 50,
		speed 		= 63,
		evolvelvl	= 33,
		moveset 	= {
					  },
	},
	{
		name 		= "Seaking",
		desc 		= "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 80,
		atk 		= 92,
		def 		= 65,
		special		= 80,
		speed 		= 68,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Staryu",
		desc 		= "An enigmatic Pokemon that can effortlessly regenerate any appendage it loses in battle.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 30,
		atk 		= 45,
		def 		= 55,
		special		= 70,
		speed 		= 85,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Starmie",
		desc 		= "	Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 60,
		atk 		= 75,
		def 		= 85,
		special		= 100,
		speed 		= 115,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Mr. Mime",
		desc 		= "If interrupted while it is miming, it will slap around the offender with its broad hands.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 40,
		atk 		= 45,
		def 		= 65,
		special		= 100,
		speed 		= 90,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Scyther",
		desc 		= "With ninja-like agility and speed, it can create the illusion that there is more than one.",
		type1 		= 13,
		type2 		= 12,
		hp 			= 70,
		atk 		= 110,
		def 		= 80,
		special		= 55,
		speed 		= 105,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Jynx",
		desc 		= "	It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.",
		type1 		= 10,
		type2 		= 6,
		hp 			= 65,
		atk 		= 50,
		def 		= 35,
		special		= 115,
		speed 		= 95,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Electabuzz",
		desc 		= "Normally found near power plants, they can wander away and cause major blackouts in cities.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 65,
		atk 		= 83,
		def 		= 57,
		special		= 85,
		speed 		= 105,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Magmar",
		desc 		= "	Its body always burns with an orange glow that enables it to hide perfectly among flames.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 65,
		atk 		= 95,
		def 		= 57,
		special		= 85,
		speed 		= 93,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Pinsir",
		desc 		= "If it fails to crush the victim in its pincers, it will swing it around and toss it hard.",
		type1 		= 13,
		type2 		= 0,
		hp 			= 65,
		atk 		= 125,
		def 		= 100,
		special		= 55,
		speed 		= 85,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Tauros",
		desc 		= "When it targets an enemy, it charges furiously while whipping its body with its long tails.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 75,
		atk 		= 100,
		def 		= 95,
		special		= 40,
		speed 		= 110,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Magikarp",
		desc 		= "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 20,
		atk 		= 10,
		def 		= 55,
		special		= 15,
		speed 		= 80,
		evolvelvl	= 20,
		moveset 	= {
					  },
	},
	{
		name 		= "Gyarados",
		desc 		= "	Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.",
		type1 		= 2,
		type2 		= 12,
		hp 			= 95,
		atk 		= 125,
		def 		= 79,
		special		= 100,
		speed 		= 81,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Lapras",
		desc 		= "A Pokemon that has been overhunted almost to extinction. It can ferry people across the water.",
		type1 		= 2,
		type2 		= 10,
		hp 			= 130,
		atk 		= 85,
		def 		= 85,
		special		= 85,
		speed 		= 60,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Ditto",
		desc 		= "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 48,
		atk 		= 48,
		def 		= 48,
		special		= 48,
		speed 		= 48,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Eevee",
		desc 		= "	Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 55,
		atk 		= 55,
		def 		= 50,
		special		= 45,
		speed 		= 55,
		evolvelvl	= -1,
		moveset 	= {
					  },
	},
	{
		name 		= "Vaporeon",
		desc 		= "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.",
		type1 		= 2,
		type2 		= 0,
		hp 			= 130,
		atk 		= 65,
		def 		= 60,
		special		= 110,
		speed 		= 65,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Jolteon",
		desc 		= "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.",
		type1 		= 3,
		type2 		= 0,
		hp 			= 65,
		atk 		= 65,
		def 		= 60,
		special		= 110,
		speed 		= 130,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Flareon",
		desc 		= "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.",
		type1 		= 8,
		type2 		= 0,
		hp 			= 65,
		atk 		= 130,
		def 		= 60,
		special		= 110,
		speed 		= 65,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Porygon",
		desc 		= "A Pokemon that consists entirely of programming code. Capable of moving freely in cyberspace.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 65,
		atk 		= 60,
		def 		= 70,
		special		= 85,
		speed 		= 40,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Omanyte",
		desc 		= "Although long extinct, in rare cases, it can be genetically resurrected from fossils.",
		type1 		= 7,
		type2 		= 2,
		hp 			= 35,
		atk 		= 40,
		def 		= 100,
		special		= 90,
		speed 		= 35,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Omastar",
		desc 		= "A prehistoric Pokemon that died out when its heavy shell made it impossible to catch prey.",
		type1 		= 7,
		type2 		= 2,
		hp 			= 70,
		atk 		= 60,
		def 		= 125,
		special		= 115,
		speed 		= 55,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Kabuto",
		desc 		= "A Pokemon that was resurrected from a fossil found in what was once the ocean floor eons ago.",
		type1 		= 7,
		type2 		= 2,
		hp 			= 30,
		atk 		= 80,
		def 		= 90,
		special		= 45,
		speed 		= 55,
		evolvelvl	= 40,
		moveset 	= {
					  },
	},
	{
		name 		= "Kabutops",
		desc 		= "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.",
		type1 		= 7,
		type2 		= 2,
		hp 			= 60,
		atk 		= 115,
		def 		= 105,
		special		= 65,
		speed 		= 80,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Aerodactyl",
		desc 		= "A ferocious, prehistoric Pokemon that goes for the enemy's throat with its serrated saw-like fangs.",
		type1 		= 7,
		type2 		= 12,
		hp 			= 80,
		atk 		= 105,
		def 		= 65,
		special		= 60,
		speed 		= 130,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Snorlax",
		desc 		= "ery lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
		type1 		= 1,
		type2 		= 0,
		hp 			= 160,
		atk 		= 110,
		def 		= 65,
		special		= 65,
		speed 		= 30,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Articuno",
		desc 		= "A legendary bird Pokemon that is said to appear to doomed people who are lost in icy mountains.",
		type1 		= 10,
		type2 		= 12,
		hp 			= 90,
		atk 		= 85,
		def 		= 100,
		special		= 125,
		speed 		= 85,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Zapdos",
		desc 		= "	A legendary bird Pokemon that is said to appear from clouds while dropping enormous lightning bolts.",
		type1 		= 3,
		type2 		= 12,
		hp 			= 90,
		atk 		= 90,
		def 		= 85,
		special		= 125,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Moltres",
		desc 		= "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.",
		type1 		= 8,
		type2 		= 12,
		hp 			= 90,
		atk 		= 100,
		def 		= 90,
		special		= 125,
		speed 		= 90,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Dratini",
		desc 		= "	Long considered a mythical Pokemon until recently when a small colony was found living underwater.",
		type1 		= 15,
		type2 		= 0,
		hp 			= 41,
		atk 		= 64,
		def 		= 45,
		special		= 50,
		speed 		= 50,
		evolvelvl	= 30,
		moveset 	= {
					  },
	},
	{
		name 		= "Dragonair",
		desc 		= "A mystical Pokemon that exudes a gentle aura. Has the ability to change climate conditions.",
		type1 		= 15,
		type2 		= 0,
		hp 			= 61,
		atk 		= 84,
		def 		= 65,
		special		= 70,
		speed 		= 70,
		evolvelvl	= 55,
		moveset 	= {
					  },
	},
	{
		name 		= "Dragonite",
		desc 		= "An extremely rarely seen marine Pokemon. Its intelligence is said to match that of humans.",
		type1 		= 15,
		type2 		= 12,
		hp 			= 91,
		atk 		= 134,
		def 		= 95,
		special		= 100,
		speed 		= 80,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Mewtwo",
		desc 		= "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 106,
		atk 		= 110,
		def 		= 90,
		special		= 154,
		speed 		= 130,
		evolvelvl	= 0,
		moveset 	= {
					  },
	},
	{
		name 		= "Mew",
		desc 		= "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.",
		type1 		= 6,
		type2 		= 0,
		hp 			= 100,
		atk 		= 100,
		def 		= 100,
		special		= 100,
		speed 		= 100,
		evolvelvl	= 0,
		moveset 	= {
					  },
	}
};
PokeTypes = {
      -- none		-- 0
	Normal 		= 1,	-- 1
	Water 		= 2,	-- 2
	Electric	= 3,	-- 3
	Fighting	= 4,	-- 4
	Ground		= 5,	-- 5
	Psychic		= 6,	-- 6
	Rock		= 7,		-- 7
	Fire		= 8,		-- 8
	Grass		= 9,	-- 9
	Ice			= 10,		-- 10
	Poison		= 11,	-- 11
	Flying		= 12,	-- 12
	Bug			= 13,		-- 13
	Ghost		= 14,	-- 14
	Dragon		= 15	-- 15
};
